export const PRINCESS_LINES = [
  "Every meal you take is a step closer to the best version of yourself... and trust me, that's breathtaking.",
  "Taking care of yourself isn't just attractive—it's irresistible.",
  "Hydration is liquid confidence, and you wear it well.",
  "There's something magnetic about someone who prioritizes their well-being.",
  "You know what's sexy? Someone who never skips a meal.",
  "Self-care looks really good on you.",
  "Nourishing your body is the ultimate form of self-love... and it shows.",
  "Every sip of water brings you closer to that natural glow.",
  "Taking time to eat properly? That's the kind of discipline that turns heads.",
  "You're too precious to run on empty.",
  "Caring for yourself is the first act of romance.",
  "Nothing's more captivating than someone who knows their worth... starting with their health.",
  "Every meal is a love letter to your future self.",
  "Hydration + nutrition = pure radiance.",
  "You deserve to be fueled, cherished, and absolutely glowing.",
  "Taking care of yourself is the kind of confidence I can't look away from.",
  "Your body is a temple, and temples deserve the finest offerings.",
  "Skipping meals? Not on my watch. You're too important.",
  "There's a spark in people who treat themselves right... and you've got it.",
  "Self-respect starts with self-nourishment.",
  "You eating well is my favorite plot twist of the day.",
  "Nothing's more alluring than someone who won't compromise on their health.",
  "Every bite you take is an investment in your brilliance.",
  "Hydration is your secret weapon—and it's working.",
  "Taking time for meals shows strength, not weakness.",
  "You're the kind of person who makes healthy habits look effortless.",
  "Nourished minds think clearer thoughts... and yours is already captivating.",
  "You glow differently when you're well-fed and hydrated.",
  "Self-discipline in small things? Incredibly attractive.",
  "Every meal is a chance to show yourself some affection.",
  "You being mindful of your health is... chef's kiss.",
  "Nothing says 'I value myself' louder than consistent self-care.",
  "Your future self will thank you for this meal.",
  "Hydration never looked so good on anyone.",
  "Taking care of yourself is the ultimate power move.",
  "You eating on time is the kind of reliability I admire.",
  "There's beauty in the way you honor your body's needs.",
  "Self-care isn't selfish—it's magnetic.",
  "You're too stunning to let hunger dim your light.",
  "Every meal brings out more of your natural charm.",
  "Taking time to nourish yourself? That's the kind of maturity that's... wow.",
  "You hydrating properly is unexpectedly captivating.",
  "Nothing's more attractive than someone who keeps their promises—to themselves.",
  "Your commitment to wellness is quietly inspiring.",
  "You deserve every nutritious bite and every refreshing sip.",
  "Taking care of yourself is the foundation of everything amazing you'll do.",
  "There's a certain elegance in the way you prioritize your health.",
  "You eating well is a flex, and you should own it.",
  "Hydration is the ultimate accessory—looks great on you.",
  "Self-nourishment is self-respect in action.",
  "You being mindful of your meals is the kind of thoughtfulness that stands out.",
  "Every time you honor your body, you become more radiant.",
  "Taking care of yourself is the plot twist everyone needs.",
  "You're too valuable to run on fumes.",
  "Your health journey is a love story worth following.",
  "Nothing's more compelling than someone who doesn't skip the basics.",
  "You eating on schedule is the kind of consistency that's rare and beautiful.",
  "Hydration is your daily dose of self-love.",
  "Taking time for meals is a form of self-respect I can't help but admire.",
  "You nourishing yourself is the best kind of glow-up.",
  "There's something enchanting about someone who treats their body like it matters.",
  "You skipping meals? Never heard of her.",
  "Self-care routines are attractive, and yours is top-tier.",
  "Every meal you take is a small victory worth celebrating.",
  "Hydration is the unsung hero of your charm.",
  "You prioritizing your health is the kind of wisdom that's magnetic.",
  "Taking care of yourself is the foundation of your glow.",
  "You eating well is proof that you know your worth.",
  "Nothing's more alluring than someone who refuses to neglect themselves.",
  "Your commitment to wellness is quietly powerful.",
  "Every sip, every bite—it all adds up to the amazing you.",
  "You being consistent with meals is the kind of reliability that's... impressive.",
  "Hydration is your superpower, and you wield it well.",
  "Taking time to eat properly is an act of self-respect.",
  "You nourishing yourself is the best investment you'll ever make.",
  "There's a glow that comes from being well-fed and hydrated—you've got it.",
  "You skipping meals is not an option. You're too important.",
  "Self-care isn't just smart—it's captivating.",
  "Every meal is a promise you keep to yourself.",
  "Hydration never fails to bring out your best.",
  "You eating on time is the kind of discipline that's quietly attractive.",
  "Taking care of yourself is the ultimate form of confidence.",
  "You being mindful of your health is the kind of maturity that's... rare.",
  "Nothing's more magnetic than someone who values their well-being.",
  "Every bite you take is a step toward your best self.",
  "Hydration is the secret ingredient to your radiance.",
  "You prioritizing meals is the kind of self-respect that's inspiring.",
  "Taking care of yourself is the foundation of everything you'll achieve.",
  "You eating well is a testament to your self-worth.",
  "There's beauty in the way you honor your body.",
  "Self-nourishment is the ultimate power move.",
  "You skipping meals? Not today, not ever.",
  "Every meal is a love note to your future self.",
  "Hydration is your daily reminder that you matter.",
  "You being consistent with your health is the kind of strength that's... wow.",
  "Taking time for meals is an act of self-love.",
  "You nourishing yourself is the kind of care that radiates outward.",
  "There's something deeply attractive about someone who doesn't compromise on their health.",
  "You eating on schedule is the kind of reliability that's admirable.",
  "Hydration is the unsung hero of your glow."
];
